-- Remplir bo_seconde avec le programme officiel
INSERT INTO public.bo_seconde (chapitre, sous_notion) VALUES
-- 1. Nombres et calculs
('Manipuler les nombres réels', 'Ensemble ℝ et ses sous-ensembles'),
('Manipuler les nombres réels', 'Intervalles de ℝ'),
('Manipuler les nombres réels', 'Valeur absolue'),
('Manipuler les nombres réels', 'Encadrements et approximations'),
('Manipuler les nombres réels', 'Nombres rationnels et irrationnels'),
('Utiliser les notions de multiple, diviseur et de nombre premier', 'Multiples et diviseurs'),
('Utiliser les notions de multiple, diviseur et de nombre premier', 'Nombres premiers'),
('Utiliser les notions de multiple, diviseur et de nombre premier', 'Décomposition en produit de facteurs premiers'),
('Utiliser le calcul littéral', 'Puissances entières et fractionnaires'),
('Utiliser le calcul littéral', 'Calculs avec radicaux'),
('Utiliser le calcul littéral', 'Identités remarquables'),
('Utiliser le calcul littéral', 'Résolution d''équations et inéquations'),
-- 2. Géométrie
('Manipuler les vecteurs du plan', 'Somme de vecteurs'),
('Manipuler les vecteurs du plan', 'Colinéarité'),
('Manipuler les vecteurs du plan', 'Coordonnées dans un repère'),
('Manipuler les vecteurs du plan', 'Déterminant de deux vecteurs'),
('Résoudre des problèmes de géométrie', 'Projeté orthogonal d''un point sur une droite'),
('Représenter et caractériser les droites du plan', 'Équation cartésienne de droite'),
('Représenter et caractériser les droites du plan', 'Équation réduite'),
('Représenter et caractériser les droites du plan', 'Pente et ordonnée à l''origine'),
('Représenter et caractériser les droites du plan', 'Systèmes linéaires 2×2'),
-- 3. Fonctions
('Se constituer un répertoire de fonctions de référence', 'Fonction carré'),
('Se constituer un répertoire de fonctions de référence', 'Fonction inverse'),
('Se constituer un répertoire de fonctions de référence', 'Fonction racine carrée'),
('Se constituer un répertoire de fonctions de référence', 'Fonction cube'),
('Représenter algébriquement et graphiquement les fonctions', 'Représentation graphique'),
('Représenter algébriquement et graphiquement les fonctions', 'Courbe représentative'),
('Représenter algébriquement et graphiquement les fonctions', 'Parité (fonctions paires et impaires)'),
('Résoudre des problèmes de variations et d''extremum', 'Sens de variation'),
('Résoudre des problèmes de variations et d''extremum', 'Tableau de variations'),
('Résoudre des problèmes de variations et d''extremum', 'Maximum et minimum'),
-- 4. Statistiques et probabilités
('Exploiter la notion d''information chiffrée', 'Proportions et pourcentages'),
('Exploiter la notion d''information chiffrée', 'Évolutions successives et réciproques'),
('Exploiter la notion d''information chiffrée', 'Moyenne pondérée'),
('Exploiter la notion d''information chiffrée', 'Écart-type'),
('Modéliser le hasard', 'Univers et événements'),
('Modéliser le hasard', 'Loi de probabilité'),
('Modéliser le hasard', 'Réunion, intersection, contraire'),
('Modéliser le hasard', 'Dénombrement par arbres ou tableaux'),
('Échantillonnage', 'Loi des grands nombres'),
('Échantillonnage', 'Principe de l''estimation'),
-- 5. Algorithmique et programmation
('Utiliser les variables et les instructions élémentaires', 'Types de variables'),
('Utiliser les variables et les instructions élémentaires', 'Affectation'),
('Utiliser les variables et les instructions élémentaires', 'Boucles (for, while)'),
('Utiliser les variables et les instructions élémentaires', 'Instructions conditionnelles (if)'),
('Concevoir et utiliser des fonctions', 'Fonctions avec arguments'),
('Concevoir et utiliser des fonctions', 'Fonctions Python de génération aléatoire'),
-- 6. Vocabulaire ensembliste et logique
('Vocabulaire ensembliste et logique', 'Appartenance (∈), inclusion (⊂)'),
('Vocabulaire ensembliste et logique', 'Intersection (⋂), réunion (⋃)'),
('Vocabulaire ensembliste et logique', 'Couples et produit cartésien'),
('Vocabulaire ensembliste et logique', 'Propositions et négation'),
('Vocabulaire ensembliste et logique', 'Contre-exemples'),
('Vocabulaire ensembliste et logique', 'Implication'),
('Vocabulaire ensembliste et logique', 'Quantificateurs universel et existentiel');

-- Remplir bo_premiere avec le programme officiel
INSERT INTO public.bo_premiere (chapitre, sous_notion) VALUES
-- 1. Algèbre
('Suites numériques', 'Modes de génération (explicite, récurrence)'),
('Suites numériques', 'Suites arithmétiques'),
('Suites numériques', 'Suites géométriques'),
('Suites numériques', 'Sens de variation'),
('Suites numériques', 'Représentation graphique'),
('Suites numériques', 'Limite intuitive (convergence, divergence vers l''infini)'),
('Polynômes du second degré', 'Forme développée, canonique, factorisée'),
('Polynômes du second degré', 'Discriminant'),
('Polynômes du second degré', 'Résolution d''équations du second degré'),
('Polynômes du second degré', 'Somme et produit des racines'),
('Polynômes du second degré', 'Signe du trinôme'),
-- 2. Analyse
('Dérivation', 'Taux de variation'),
('Dérivation', 'Nombre dérivé en un point'),
('Dérivation', 'Équation de tangente'),
('Dérivation', 'Fonction dérivée'),
('Dérivation', 'Dérivées des fonctions usuelles'),
('Dérivation', 'Opérations sur les dérivées'),
('Dérivation', 'Dérivée de fonctions composées (du type u^n, 1/u)'),
('Dérivation', 'Fonction dérivée de x ↦ g(ax+b)'),
('Dérivation', 'Lien entre signe de la dérivée et variations'),
('Fonction exponentielle', 'Définition (f'' = f et f(0) = 1)'),
('Fonction exponentielle', 'Propriétés algébriques'),
('Fonction exponentielle', 'Nombre e'),
('Fonction exponentielle', 'Notation exp(x) = e^x'),
('Fonction exponentielle', 'Lien avec les suites géométriques'),
('Fonctions trigonométriques', 'Cercle trigonométrique'),
('Fonctions trigonométriques', 'Radian'),
('Fonctions trigonométriques', 'Enroulement de la droite sur le cercle'),
('Fonctions trigonométriques', 'Fonctions cosinus et sinus'),
('Fonctions trigonométriques', 'Parité et périodicité'),
('Fonctions trigonométriques', 'Valeurs remarquables'),
-- 3. Géométrie
('Produit scalaire', 'Définition à partir de la projection orthogonale'),
('Produit scalaire', 'Formule avec le cosinus'),
('Produit scalaire', 'Bilinéarité et symétrie'),
('Produit scalaire', 'Expression dans une base orthonormée'),
('Produit scalaire', 'Théorème d''Al-Kashi'),
('Produit scalaire', 'Transformation d''écritures vectorielles'),
('Géométrie repérée', 'Vecteur normal à une droite'),
('Géométrie repérée', 'Équation du cercle'),
('Géométrie repérée', 'Parabole représentant une fonction du second degré'),
-- 4. Probabilités et statistiques
('Probabilités conditionnelles', 'Notation P_A(B)'),
('Probabilités conditionnelles', 'Indépendance de deux événements'),
('Probabilités conditionnelles', 'Arbres pondérés'),
('Probabilités conditionnelles', 'Partition de l''univers'),
('Probabilités conditionnelles', 'Formule des probabilités totales'),
('Probabilités conditionnelles', 'Succession de deux épreuves indépendantes'),
('Variables aléatoires réelles', 'Définition (fonction sur l''univers)'),
('Variables aléatoires réelles', 'Loi de probabilité'),
('Variables aléatoires réelles', 'Espérance'),
('Variables aléatoires réelles', 'Variance et écart-type'),
('Expérimentations et simulations', 'Simulations en Python'),
('Expérimentations et simulations', 'Moyenne d''un échantillon'),
('Expérimentations et simulations', 'Distance entre moyenne et espérance'),
('Expérimentations et simulations', 'Proportion de valeurs dans l''intervalle [μ - 2σ/√n ; μ + 2σ/√n]'),
-- 5. Algorithmique et programmation
('Manipuler les listes', 'Génération par extension et en compréhension'),
('Manipuler les listes', 'Manipulation d''éléments et d''indices'),
('Manipuler les listes', 'Parcours de listes'),
('Manipuler les listes', 'Itération sur les éléments'),
-- 6. Vocabulaire ensembliste et logique
('Vocabulaire ensembliste et logique', 'Couple et produit cartésien'),
('Vocabulaire ensembliste et logique', 'Complémentaire d''une partie'),
('Vocabulaire ensembliste et logique', 'Connecteurs logiques "et" / "ou"'),
('Vocabulaire ensembliste et logique', 'Condition nécessaire et condition suffisante'),
('Vocabulaire ensembliste et logique', 'Statut des égalités (identité / équation)'),
('Vocabulaire ensembliste et logique', 'Statut des lettres (variable / inconnue / paramètre)'),
('Vocabulaire ensembliste et logique', 'Quantificateurs (universel et existentiel)'),
('Vocabulaire ensembliste et logique', 'Négation de propositions quantifiées'),
('Vocabulaire ensembliste et logique', 'Raisonnements (par disjonction de cas, par l''absurde, par contraposée)');

-- Remplir bo_terminale avec le programme officiel
INSERT INTO public.bo_terminale (chapitre, sous_notion) VALUES
-- 1. Algèbre et géométrie
('Combinatoire et dénombrement', 'Principe additif et principe multiplicatif'),
('Combinatoire et dénombrement', 'k-uplets'),
('Combinatoire et dénombrement', 'Nombre de parties d''un ensemble fini'),
('Combinatoire et dénombrement', 'Permutations et factorielle'),
('Combinatoire et dénombrement', 'Combinaisons'),
('Combinatoire et dénombrement', 'Triangle de Pascal'),
('Manipuler les vecteurs de l''espace', 'Translation dans l''espace'),
('Manipuler les vecteurs de l''espace', 'Coplanarité'),
('Manipuler les vecteurs de l''espace', 'Décomposition dans une base'),
('Manipuler les vecteurs de l''espace', 'Repérage dans l''espace'),
('Produit scalaire dans l''espace', 'Définition et propriétés'),
('Produit scalaire dans l''espace', 'Expression dans une base orthonormée'),
('Produit scalaire dans l''espace', 'Orthogonalité dans l''espace'),
('Produit scalaire dans l''espace', 'Vecteur normal à un plan'),
('Produit scalaire dans l''espace', 'Projeté orthogonal sur un plan'),
('Géométrie repérée dans l''espace', 'Représentation paramétrique d''une droite'),
('Géométrie repérée dans l''espace', 'Équation cartésienne d''un plan'),
('Géométrie repérée dans l''espace', 'Systèmes d''équations linéaires'),
-- 2. Analyse
('Suites numériques', 'Limite finie ou infinie'),
('Suites numériques', 'Convergence et divergence'),
('Suites numériques', 'Limites et comparaison'),
('Suites numériques', 'Théorème des gendarmes'),
('Suites numériques', 'Opérations sur les limites'),
('Suites numériques', 'Limite de q^n'),
('Suites numériques', 'Suite croissante majorée'),
('Limites de fonctions', 'Limite finie ou infinie en l''infini ou en un point'),
('Limites de fonctions', 'Asymptotes'),
('Limites de fonctions', 'Croissances comparées'),
('Limites de fonctions', 'Opérations sur les limites'),
('Compléments sur la dérivation', 'Dérivée d''une fonction composée'),
('Compléments sur la dérivation', 'Dérivée seconde'),
('Compléments sur la dérivation', 'Convexité'),
('Compléments sur la dérivation', 'Point d''inflexion'),
('Continuité', 'Définition par les limites'),
('Continuité', 'Fonction dérivable continue'),
('Continuité', 'Image d''une suite convergente'),
('Continuité', 'Théorème des valeurs intermédiaires'),
('Continuité', 'Cas des fonctions continues strictement monotones'),
('Fonction logarithme népérien', 'Fonction réciproque de l''exponentielle'),
('Fonction logarithme népérien', 'Propriétés algébriques'),
('Fonction logarithme népérien', 'Dérivée'),
('Fonction logarithme népérien', 'Limites en 0 et en +∞'),
('Fonction logarithme népérien', 'Croissances comparées'),
('Fonctions sinus et cosinus', 'Dérivées'),
('Fonctions sinus et cosinus', 'Variations'),
('Fonctions sinus et cosinus', 'Résolution d''équations trigonométriques'),
('Primitives et équations différentielles', 'Équations du type y'' = f'),
('Primitives et équations différentielles', 'Primitives des fonctions usuelles'),
('Primitives et équations différentielles', 'Équations différentielles y'' = ay'),
('Primitives et équations différentielles', 'Équations différentielles y'' = ay + b'),
('Calcul intégral', 'Intégrale d''une fonction continue positive'),
('Calcul intégral', 'Notation ∫ₐᵇ f(x)dx'),
('Calcul intégral', 'Primitive s''annulant en a'),
('Calcul intégral', 'Calcul d''intégrale à l''aide de primitives'),
('Calcul intégral', 'Linéarité de l''intégrale'),
('Calcul intégral', 'Relation de Chasles'),
('Calcul intégral', 'Valeur moyenne'),
('Calcul intégral', 'Intégration par parties'),
-- 3. Probabilités
('Succession d''épreuves indépendantes (schéma de Bernoulli)', 'Épreuve de Bernoulli'),
('Succession d''épreuves indépendantes (schéma de Bernoulli)', 'Schéma de Bernoulli'),
('Succession d''épreuves indépendantes (schéma de Bernoulli)', 'Loi binomiale'),
('Succession d''épreuves indépendantes (schéma de Bernoulli)', 'Coefficients binomiaux'),
('Sommes de variables aléatoires', 'Linéarité de l''espérance'),
('Sommes de variables aléatoires', 'Variance de sommes (cas indépendant)'),
('Sommes de variables aléatoires', 'Loi binomiale (espérance, variance, écart-type)'),
('Sommes de variables aléatoires', 'Échantillon et moyenne empirique'),
('Concentration et loi des grands nombres', 'Inégalité de Bienaymé-Tchebychev'),
('Concentration et loi des grands nombres', 'Inégalité de concentration'),
('Concentration et loi des grands nombres', 'Loi des grands nombres'),
-- 4. Algorithmique et programmation
('Manipuler les listes', 'Génération par extension et en compréhension'),
('Manipuler les listes', 'Manipulation d''éléments et d''indices'),
('Manipuler les listes', 'Parcours de listes'),
('Manipuler les listes', 'Itération sur les éléments'),
-- 5. Vocabulaire ensembliste et logique
('Vocabulaire ensembliste et logique', 'k-uplet et produit cartésien'),
('Vocabulaire ensembliste et logique', 'Négation de propositions avec quantificateurs'),
('Vocabulaire ensembliste et logique', 'Contraposée, équivalence'),
('Vocabulaire ensembliste et logique', 'Propriété caractéristique'),
('Vocabulaire ensembliste et logique', 'Condition nécessaire et suffisante'),
('Vocabulaire ensembliste et logique', 'Raisonnement par récurrence');